# Prof Y Not - Sitemap Regeneration
# Regenerates sitemap weekly and pings search engines

name: Weekly Sitemap Update

on:
  schedule:
    # Run every Sunday at midnight UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

env:
  HUGO_VERSION: 0.124.0

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Build site
        run: hugo --gc --minify

      - name: Ping Google
        run: |
          curl -s "https://www.google.com/ping?sitemap=https://profynot.github.io/sitemap.xml"
          echo "Pinged Google"

      - name: Ping Bing
        run: |
          curl -s "https://www.bing.com/ping?sitemap=https://profynot.github.io/sitemap.xml"
          echo "Pinged Bing"

      - name: Log completion
        run: echo "Sitemap update complete at $(date)"
